site_name: LEADR Docs
site_url: https://docs.leadr.gg
site_description: Documentation for LEADR - a cross-platform leaderboard backend for indie game developers
site_author: LEADR
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
plugins:
  - search
  - autorefs
  - section-index
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

site_dir: site-md

nav:
  - Overview: index.md
  - Concepts: concepts.md
  - API:
      - Overview: api/index.md
      - Patterns: api/patterns.md
      - Reference: api/reference.md
  - SDKs:
      - Overview: sdks/index.md
  - About: about.md
  - Changelog: changelog.md

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/leadr-official.bsky.social
      name: LEADR on Bluesky
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@LEADR_official
      name: LEADR on Mastodon
    - icon: fontawesome/brands/github
      link: https://github.com/LEADR-official
      name: LEADR on GitHub
